In [2]:
# Create an 1d array from a list

import numpy as np
list1 = [0,1,2,3,4]
arr1d = np.array(list1)

# Print the array and its type
print(type(arr1d))

# Add 2 to each element of arr1d
arr1d = arr1d + 2
print(arr1d)

<class 'numpy.ndarray'>
[2 3 4 5 6]


In [3]:
# Create a 2d array from a list of lists
list2 = [[0,1,2], [3,4,5], [6,7,8]]
arr2d = np.array(list2)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# Create a float 2d array
arr2d_f = np.array(list2, dtype='float')
print(arr2d_f)

# Convert to 'int' datatype
arr2d_i = arr2d_f.astype('int')
print(arr2d_i)

# Convert to int then to str datatype
arr2d_s = arr2d_f.astype('int').astype('str')
print(arr2d_s)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
