In [1]:
# min-max normalization & standardisation
# Import packages
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import preprocessing

In [8]:
ds = pd.read_csv('C:\\Users\sushant\data_for_missing_values.csv')
ds.head(20)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [11]:
# Replace NaN with 0.
# Age and Salary columns are taken using slicing to handle values with varying magnitude
ds.fillna(0, inplace=True)
x=ds.iloc[:, 1:3].values
print("\nOriginal data values : \n", x)


Original data values : 
 [[4.4e+01 7.2e+04]
 [2.7e+01 4.8e+04]
 [3.0e+01 5.4e+04]
 [3.8e+01 6.1e+04]
 [4.0e+01 0.0e+00]
 [3.5e+01 5.8e+04]
 [0.0e+00 5.2e+04]
 [4.8e+01 7.9e+04]
 [5.0e+01 8.3e+04]
 [3.7e+01 6.7e+04]]


In [12]:
# MIN MAX SCALER
min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1))
# Scaled feature
x_after_min_max_scaler = min_max_scaler.fit_transform(x)
 
print("\nAfter min max Scaling : \n", x_after_min_max_scaler)


After min max Scaling : 
 [[0.88       0.86746988]
 [0.54       0.57831325]
 [0.6        0.65060241]
 [0.76       0.73493976]
 [0.8        0.        ]
 [0.7        0.69879518]
 [0.         0.62650602]
 [0.96       0.95180723]
 [1.         1.        ]
 [0.74       0.80722892]]


In [13]:
# Standardisation
Standardisation = preprocessing.StandardScaler()
# Scaled feature
x_after_Standardisation = Standardisation.fit_transform(x)
 
print ("\nAfter Standardisation : \n", x_after_Standardisation)


After Standardisation : 
 [[ 0.67326185  0.66196986]
 [-0.58448007 -0.42619977]
 [-0.36252561 -0.15415736]
 [ 0.22935294  0.16322544]
 [ 0.37732257 -2.60253904]
 [ 0.00739848  0.02720424]
 [-2.58207016 -0.24483817]
 [ 0.96920112  0.97935267]
 [ 1.11717076  1.16071427]
 [ 0.15536812  0.43526785]]
